baseURL = "https://www.edsautodetailing.com/"
languageCode = "en-us"
title = "Ed's Auto Detailing"
theme = "blank"

disableKinds = ["taxonomy", "taxonomyTerm"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
    [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

    [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services"
    weight = 2

    [[menu.main]]
    identifier = "faqs"
    name = "FAQs"
    url = "/frequently-asked-questions"
    weight = 3

    [[menu.main]]
    identifier = "hours"
    name = "Hours"
    url = "/hours"
    weight = 4

    [[menu.main]]
    identifier = "location"
    name = "Location"
    url = "/location"
    weight = 5

    [[menu.main]]
    identifier = "contact-us"
    name = "Contact Us"
    url = "/contact-us"
    weight = 6

    [[menu.main]]
    identifier = "the-full-detail"
    name = "The Full Detail"
    parent = "services"
    url = "/services/the-full-detail"
    weight = 1

    [[menu.main]]
    identifier = "interior-deep-clean"
    name = "Interior Deep Clean"
    parent = "services"
    url="/services/interior-deep-clean"
    weight = 2

    [[menu.main]]
    identifier = "exterior-refresh"
    name = "Exterior Refresh"
    parent = "services"
    url="/services/exterior-refresh"
    weight = 3

    [[menu.main]]
    identifier = "headlight-restoration"
    name = "Headlight Restoration"
    parent = "services"
    url="/services/headlight-restoration"
    weight = 4

    [[menu.main]]
    identifier = "interior-spill-cleanup"
    name = "Interior Spill Cleanup"
    parent = "services"
    url="/services/interior-spill-cleanup"
    weight = 5

    [[menu.main]]
    identifier = "vinyl-decal-removal"
    name = "Vinyl / Decal Removal"
    parent = "services"
    url="/services/vinyl-decal-removal"
    weight = 6