[build]
  publish = "public"
  command = "command = "hugo --gc --minify --buildFuture -b https://5e95d0cc2f3b53000764b0f5--stupefied-blackwell-4e6598.netlify.com/"

[context.production.environment]
  HUGO_VERSION = "0.53"
